# version: '3.8'
# services:
#   postgres:
#     image: postgres:12
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#   api:
#     build:
#       context: ../
#       dockerfile: docker/Dockerfile.api
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#   front:
#     build:
#       context: ../
#       dockerfile: docker/Dockerfile.front
#     ports:
#       - "3001:3000"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#       - FAST_REFRESH=false
#     depends_on:
#       - api

# version: '3.8'
# services:
#   postgres:
#     image: postgres:12
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#   api:
#     build:
#       context: ../
#       dockerfile: docker/Dockerfile.api
#     volumes:
#       - ./api/uploads:/usr/src/app/uploads
#       - ../api:/usr/src/app
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#   front:
#     build:
#       context: ../
#       dockerfile: docker/Dockerfile.front
#     volumes:
#       - ../front:/usr/src/app
#     ports:
#       - "3001:3000"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
      
#       - FAST_REFRESH=false
#     depends_on:
#       - api

version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    volumes:
      # - ./api/uploads:/usr/uploads
      # - ./api/uploads:/usr/src/app/uploads
      - ../api:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DB_PORT: 5432
    networks:
      - app-network
    depends_on:
      - postgres
  front:
    build:
      context: ../
      dockerfile: docker/Dockerfile.front
    volumes:
      - ../front:/usr/src/app
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
    depends_on:
      - api
networks:
  app-network:
    driver: bridge

